### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by prerna-agg** [prerna-agg/snakes_and_ladder#1]
Good first issue to edit readme.md

**Comment by hi-18-K** [comment]
Can I work on this?

**Comment by prerna-agg** [comment]
> Can I work on this?

Yes

**Comment by hi-18-K** [comment]
have you published this code somewhere? If yes could you provide me with link or ss. Or I should add instructions how to run in terminal/command line?
(for updating the readme)

**Comment by prerna-agg** [comment]
> have you published this code somewhere? If yes could you provide me with link or ss. Or I should add instructions how to run in terminal/command line?
> (for updating the readme)

No I had not published it anywhere, you can add instructions

**Comment by hi-18-K** [comment]
do the user has to play snake and ladder in command line/terminal itself?

**Comment by hi-18-K** [comment]
> do the user has to play snake and ladder in command line/terminal itself?

like how does it work? could you provide me with some demonstration etc, some tutorial link or anything like that?

**Comment by prerna-agg** [comment]
I made the game using Turbo C++ software, it just ran normally as we run any c++ program

**Comment by prerna-agg** [comment]
Sorry ,I donot have any tutorial link

**Comment by prerna-agg** [comment]
graphics.h was already installed in Turbo C++

**Comment by prerna-agg** [comment]
Its a two player game , and code logic is basically dependent on quotient and remainder, to calculate the position of players circle

**Comment by prerna-agg** [comment]
read me updated
